//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vatas_DAL
{
    using System;
    
    public partial class proc_GetUserRoleByUserId_Result1
    {
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Role_Name { get; set; }
    }
}
