//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vatas_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProcessesHistoryofjob
    {
        public int ID { get; set; }
        public Nullable<long> MasterID { get; set; }
        public Nullable<long> Next_UserID { get; set; }
        public Nullable<long> Previous_UserID { get; set; }
        public string Date_Time_Stamp { get; set; }
        public Nullable<long> Priority_of_Job { get; set; }
        public string Job_Status { get; set; }
        public string Reason_for_Delay { get; set; }
        public string Supervisor { get; set; }
        public string Is_Sent { get; set; }
        public string PRN_No { get; set; }
    }
}
