//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vatas_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserGroup_Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_UserGroup_Registration()
        {
            this.tbl_UserRoles = new HashSet<tbl_UserRoles>();
        }
    
        public int Super_User_Id { get; set; }
        public string Name { get; set; }
        public string Last_Name { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
        public string Confirm_Password { get; set; }
        public string Address1 { get; set; }
        public string Country { get; set; }
        public int State { get; set; }
        public string City { get; set; }
        public int PinCode { get; set; }
        public string MobileNumber { get; set; }
        public int STDCODE { get; set; }
        public string Telephone { get; set; }
        public string OrganizationName { get; set; }
        public string SecurityQuestion { get; set; }
        public string Answer { get; set; }
        public string SelectPackage { get; set; }
        public string ActivationCode { get; set; }
        public string STATUS { get; set; }
        public string Join_Date { get; set; }
        public string Account_Type { get; set; }
        public string Is_Login_Active { get; set; }
        public Nullable<int> ID_Admin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UserRoles> tbl_UserRoles { get; set; }
    }
}
