//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vatas_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User_Transaction
    {
        public int ID { get; set; }
        public string Table_Name { get; set; }
        public string Database_Name { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string Time_Stamp { get; set; }
        public string Action { get; set; }
        public Nullable<int> Page_ID { get; set; }
        public Nullable<int> Page_SubModule_ID { get; set; }
    }
}
