//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vatas_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserMenu
    {
        public int Record_No { get; set; }
        public int Role_ID { get; set; }
        public int Menu_ID { get; set; }
        public Nullable<int> Page_ID { get; set; }
        public Nullable<int> SubModule_ID { get; set; }
        public string Menu_Status { get; set; }
        public Nullable<int> Menu_Level { get; set; }
        public Nullable<int> ID_Admin { get; set; }
    }
}
