//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vatas_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Menu
    {
        public int Menu_id { get; set; }
        public int Parent_Menu { get; set; }
        public int Menu_Level { get; set; }
        public string Menu_Name { get; set; }
        public string Menu_Link { get; set; }
        public int Menu_Order { get; set; }
        public int Menu_Status { get; set; }
        public string Is_Deleted { get; set; }
        public string Project_Name { get; set; }
        public Nullable<int> Page_ID { get; set; }
        public Nullable<int> Sub_ModuleID { get; set; }
        public Nullable<int> ID_Admin { get; set; }
        public string ITRCheck { get; set; }
        public string AssesseeCheck { get; set; }
        public string AY { get; set; }
        public string url { get; set; }
    }
}
