//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vatas_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User_Info
    {
        public int User_Info_ID { get; set; }
        public string Can_Change_Password { get; set; }
        public string Role { get; set; }
        public string Is_Locked { get; set; }
        public Nullable<int> Consecutive_Attempts { get; set; }
        public string Is_Deleted { get; set; }
        public Nullable<int> ID_Admin { get; set; }
    }
}
