//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vatas_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Path
    {
        public int Path_ID { get; set; }
        public string Path_Name { get; set; }
        public string Host { get; set; }
        public string Path { get; set; }
        public string Path_Project { get; set; }
        public Nullable<int> ID_Admin { get; set; }
    }
}
